# Generated by Django 4.2.8 on 2026-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Wholesale", "Wholesale"),
                            ("Events & Workshops", "Events & Workshops"),
                            ("Feedback", "Feedback"),
                        ],
                        default="General",
                        max_length=40,
                    ),
                ),
                ("message", models.TextField(max_length=800)),
                ("submitted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        help_text="Stable id used by the storefront, e.g. m-001",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Signature Lattes", "Signature Lattes"),
                            ("Milk Teas", "Milk Teas"),
                            ("Pure Teas", "Pure Teas"),
                            ("Iced & Sparkling", "Iced & Sparkling"),
                            ("Bakery & Bites", "Bakery & Bites"),
                            ("Extras", "Extras"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a photo for this menu item. Overrides the CDN URL when set.",
                        upload_to="menu/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional remote image URL used when no file is uploaded.",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "caffeine",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        default="Medium",
                        max_length=12,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
                ),
                ("badge", models.CharField(blank=True, max_length=40)),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Show on the homepage grid"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
