from django.core.management.base import BaseCommand
from django.contrib.auth.models import User

from catalog.models import MenuItem

SEED = [
    {
        "public_id": "m-001",
        "name": "Uji Ceremonial Matcha Latte",
        "category": "Signature Lattes",
        "description": "Stone-milled Uji matcha whisked to a fine foam over steamed oat or whole milk.",
        "price": "6.50",
        "image_url": "https://images.unsplash.com/photo-1515823662972-da6a2e4d3000?auto=format&fit=crop&w=900&q=80",
        "tags": ["Matcha", "Vegan option"],
        "caffeine": "Medium",
        "rating": "4.9",
        "badge": "Best Seller",
        "featured": True,
        "sort_order": 1,
    },
    {
        "public_id": "m-002",
        "name": "Hojicha Cloud Latte",
        "category": "Signature Lattes",
        "description": "Charcoal-roasted hojicha with a toasted-nut finish and a cloud of cold foam.",
        "price": "6.25",
        "image_url": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=80",
        "tags": ["Roasted", "Low caffeine"],
        "caffeine": "Low",
        "rating": "4.8",
        "badge": "",
        "featured": True,
        "sort_order": 2,
    },
    {
        "public_id": "m-003",
        "name": "Brown Sugar Matcha",
        "category": "Signature Lattes",
        "description": "Ceremonial matcha poured over house brown-sugar syrup and layered milk.",
        "price": "6.75",
        "image_url": "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=900&q=80",
        "tags": ["Sweet", "Matcha"],
        "caffeine": "Medium",
        "rating": "4.8",
        "badge": "New",
        "featured": True,
        "sort_order": 3,
    },
    {
        "public_id": "m-004",
        "name": "Yuzu Earl Grey Latte",
        "category": "Signature Lattes",
        "description": "Bergamot-forward Earl Grey with a bright hit of yuzu peel and steamed milk.",
        "price": "6.00",
        "image_url": "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=900&q=80",
        "tags": ["Citrus", "Floral"],
        "caffeine": "Medium",
        "rating": "4.6",
        "badge": "",
        "featured": False,
        "sort_order": 4,
    },
    {
        "public_id": "m-005",
        "name": "Classic Assam Milk Tea",
        "category": "Milk Teas",
        "description": "Malty Assam steeped strong, shaken with milk and your choice of sweetness.",
        "price": "5.50",
        "image_url": "https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=900&q=80",
        "tags": ["Classic", "Black tea"],
        "caffeine": "High",
        "rating": "4.7",
        "badge": "",
        "featured": False,
        "sort_order": 5,
    },
    {
        "public_id": "m-006",
        "name": "Brown Sugar Boba",
        "category": "Milk Teas",
        "description": "Hand-rolled tapioca pearls in burnt sugar syrup with Assam milk tea.",
        "price": "6.25",
        "image_url": "https://images.unsplash.com/photo-1558857563-c0c6d6c8e83d?auto=format&fit=crop&w=900&q=80",
        "tags": ["Boba", "Sweet"],
        "caffeine": "Medium",
        "rating": "4.9",
        "badge": "Best Seller",
        "featured": True,
        "sort_order": 6,
    },
    {
        "public_id": "m-007",
        "name": "Taro Milk Tea",
        "category": "Milk Teas",
        "description": "Real taro, not flavouring — earthy, purple and softly sweet.",
        "price": "6.00",
        "image_url": "https://images.unsplash.com/photo-1525385133512-2f3bdd03954e?auto=format&fit=crop&w=900&q=80",
        "tags": ["Taro", "Creamy"],
        "caffeine": "Low",
        "rating": "4.5",
        "badge": "",
        "featured": False,
        "sort_order": 7,
    },
    {
        "public_id": "m-008",
        "name": "Roasted Oolong Milk Tea",
        "category": "Milk Teas",
        "description": "Nantou oolong charcoal-roasted in 2kg batches, then shaken with milk.",
        "price": "6.25",
        "image_url": "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=900&q=80",
        "tags": ["Oolong", "Roasted"],
        "caffeine": "Medium",
        "rating": "4.7",
        "badge": "",
        "featured": False,
        "sort_order": 8,
    },
    {
        "public_id": "m-009",
        "name": "Ali Shan High Mountain",
        "category": "Pure Teas",
        "description": "Floral high-mountain oolong, gongfu-style, three steeps in the pot.",
        "price": "7.50",
        "image_url": "https://images.unsplash.com/photo-1564890369478-c89ca4d58400?auto=format&fit=crop&w=900&q=80",
        "tags": ["Oolong", "Single estate"],
        "caffeine": "Medium",
        "rating": "4.8",
        "badge": "",
        "featured": True,
        "sort_order": 9,
    },
    {
        "public_id": "m-010",
        "name": "Gyokuro",
        "category": "Pure Teas",
        "description": "Shade-grown, steamed, and poured at 60°C. Sweet, marine and quiet.",
        "price": "8.50",
        "image_url": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=900&q=80",
        "tags": ["Green", "Ceremonial"],
        "caffeine": "High",
        "rating": "4.9",
        "badge": "",
        "featured": False,
        "sort_order": 10,
    },
    {
        "public_id": "m-011",
        "name": "White Peony",
        "category": "Pure Teas",
        "description": "Fuding bai mu dan — honeyed, apricot, and almost no astringency.",
        "price": "6.50",
        "image_url": "https://images.unsplash.com/photo-1597318181408-fc64d0b5d8a1?auto=format&fit=crop&w=900&q=80",
        "tags": ["White", "Delicate"],
        "caffeine": "Low",
        "rating": "4.6",
        "badge": "",
        "featured": False,
        "sort_order": 11,
    },
    {
        "public_id": "m-012",
        "name": "Charcoal Hojicha",
        "category": "Pure Teas",
        "description": "Our own binchōtan roast. Toasted rice, cocoa husk, almost no caffeine.",
        "price": "5.75",
        "image_url": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80",
        "tags": ["Roasted", "Evening"],
        "caffeine": "None",
        "rating": "4.7",
        "badge": "",
        "featured": False,
        "sort_order": 12,
    },
    {
        "public_id": "m-013",
        "name": "Matcha Lemonade",
        "category": "Iced & Sparkling",
        "description": "Ceremonial matcha shaken with yuzu-bright lemonade over pebble ice.",
        "price": "6.25",
        "image_url": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=80",
        "tags": ["Iced", "Citrus"],
        "caffeine": "Medium",
        "rating": "4.9",
        "badge": "Guest favourite",
        "featured": True,
        "sort_order": 13,
    },
    {
        "public_id": "m-014",
        "name": "Yuzu Sparkling Sencha",
        "category": "Iced & Sparkling",
        "description": "Cold-brew sencha topped with sparkling water and a twist of yuzu.",
        "price": "5.75",
        "image_url": "https://images.unsplash.com/photo-1556679343-c1c1c9308bb4?auto=format&fit=crop&w=900&q=80",
        "tags": ["Sparkling", "Green"],
        "caffeine": "Low",
        "rating": "4.5",
        "badge": "",
        "featured": False,
        "sort_order": 14,
    },
    {
        "public_id": "m-015",
        "name": "Cold Brew Jasmine",
        "category": "Iced & Sparkling",
        "description": "Eight-hour cold brew over jade jasmine pearls. Floral, never soapy.",
        "price": "5.50",
        "image_url": "https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=900&q=80",
        "tags": ["Cold brew", "Floral"],
        "caffeine": "Low",
        "rating": "4.6",
        "badge": "",
        "featured": False,
        "sort_order": 15,
    },
    {
        "public_id": "m-016",
        "name": "Sparkling Peach Oolong",
        "category": "Iced & Sparkling",
        "description": "Light oolong, white peach, and a splash of soda. Summer in a glass.",
        "price": "6.00",
        "image_url": "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=900&q=80",
        "tags": ["Sparkling", "Fruit"],
        "caffeine": "Low",
        "rating": "4.4",
        "badge": "New",
        "featured": False,
        "sort_order": 16,
    },
    {
        "public_id": "m-017",
        "name": "Hojicha Basque Cheesecake",
        "category": "Bakery & Bites",
        "description": "Burnt-top cheesecake with spent-hojicha crumb. Rosa's signature.",
        "price": "6.50",
        "image_url": "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=900&q=80",
        "tags": ["Pastry", "Roasted"],
        "caffeine": "None",
        "rating": "4.9",
        "badge": "Best Seller",
        "featured": True,
        "sort_order": 17,
    },
    {
        "public_id": "m-018",
        "name": "Matcha Financiers",
        "category": "Bakery & Bites",
        "description": "Almond brown-butter cakes with a crease of ceremonial matcha.",
        "price": "4.25",
        "image_url": "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=900&q=80",
        "tags": ["Pastry", "Matcha"],
        "caffeine": "Low",
        "rating": "4.6",
        "badge": "",
        "featured": False,
        "sort_order": 18,
    },
    {
        "public_id": "m-019",
        "name": "Genmaicha Cookie",
        "category": "Bakery & Bites",
        "description": "Toasted-rice tea folded into a shortbread. Dip it in hojicha.",
        "price": "3.50",
        "image_url": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=900&q=80",
        "tags": ["Cookie", "Toasted"],
        "caffeine": "None",
        "rating": "4.5",
        "badge": "",
        "featured": False,
        "sort_order": 19,
    },
    {
        "public_id": "m-020",
        "name": "Earl Grey Scone",
        "category": "Bakery & Bites",
        "description": "Bergamot cream scone with a pot of the same tea on the side.",
        "price": "4.75",
        "image_url": "https://images.unsplash.com/photo-1486428186368-9e0fde67534d?auto=format&fit=crop&w=900&q=80",
        "tags": ["Scone", "Floral"],
        "caffeine": "Low",
        "rating": "4.4",
        "badge": "",
        "featured": False,
        "sort_order": 20,
    },
    {
        "public_id": "m-021",
        "name": "Extra Boba",
        "category": "Extras",
        "description": "A scoop of hand-rolled pearls in brown sugar, for any milk tea.",
        "price": "1.25",
        "image_url": "https://images.unsplash.com/photo-1525385133512-2f3bdd03954e?auto=format&fit=crop&w=900&q=80",
        "tags": ["Add-on"],
        "caffeine": "None",
        "rating": "4.7",
        "badge": "",
        "featured": False,
        "sort_order": 21,
    },
    {
        "public_id": "m-022",
        "name": "Extra Ceremonial Shot",
        "category": "Extras",
        "description": "A second whisk of Uji ceremonial matcha in any latte or lemonade.",
        "price": "1.75",
        "image_url": "https://images.unsplash.com/photo-1515823662972-da6a2e4d3000?auto=format&fit=crop&w=900&q=80",
        "tags": ["Add-on", "Matcha"],
        "caffeine": "Medium",
        "rating": "4.8",
        "badge": "",
        "featured": False,
        "sort_order": 22,
    },
]


class Command(BaseCommand):
    help = "Seed 22 menu items and create a staff admin user if missing."

    def handle(self, *args, **options):
        for row in SEED:
            MenuItem.objects.update_or_create(public_id=row["public_id"], defaults=row)
        self.stdout.write(self.style.SUCCESS(f"Seeded {len(SEED)} menu items."))

        if not User.objects.filter(username="admin").exists():
            User.objects.create_superuser("admin", "admin@kocha.co", "admin123")
            self.stdout.write(self.style.SUCCESS("Created staff user admin / admin123"))
        else:
            self.stdout.write("Staff user 'admin' already exists.")
